dist: trusty
sudo: required
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

#addons:
#  apt:
#    packages:
#      - gcc-9
#      - g++-9

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURETION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    - os: osx
      compiler: gcc

    - os: osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

    - os: osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  - source ci/travis/install-$TRAVIS_OS_NAME.sh

before_script:
  - mkdir -p build
  - cd build
  - cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU

script:
  # TODO: bash -e ci/travis/set-env.sh
  - cmake --build .
  - ctest --output-on-failure

#deploy:
#  provider: releases
#  file: build/libfsdb.so
#  skip_cleanup: true
#  overwrite: true
#
#  api_key:
#    secure: <encrypted-github-token>
#
#  on:
#    tags: true

